#!/bin/bash
# name: CA Setup
# description: Installs the local Root CA into your macOS Keychain

echo "🛡️  Installing Local Certificate Authority..."

# Install mkcert CA into system trust store
mkcert -install

echo "✅ Your Mac now trusts certificates generated by mkcert."
echo "💡 Note: You may need to restart your browser (especially Firefox) to see the changes."
